version: '3.7'
services:
  api:
    build: ./api_biblioteca
    ports:
      - "5555:5555"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./api_biblioteca/docker_db
        target: /docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: db_library
      MYSQL_USER: library
      MYSQL_ROOT_PASSWORD: library
      MYSQL_PASSWORD: library
  front:
    build: ./vue_biblioteca
    ports:
      - "8000:8080"
    command: npm run serve

volumes:
  db:
    